version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: fast-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: fast_db
      MYSQL_USER: fastteamjpsm
      MYSQL_PASSWORD: fast!jpsm
    ports:
      - "13306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data: